server: server.c message.c clientDB.c eventHandler.c connectionDB.c
	gcc server.c message.c clientDB.c eventHandler.c connectionDB.c -o server

client: client.c message.c
	gcc client.c message.c -o client
